version: "3.7"
services:
  web:
    build: ./drf_wallet_app
    ports:
      - "8000:8000"
    volumes:
      - ./drf_wallet_app/app:/app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    env_file: .env
    environment:
      - DEBUG=TRUE
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
