# Generated by Django 4.1.2 on 2022-11-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_alter_wallets_user_alter_wallets_wallet_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wallets",
            name="card_type",
            field=models.CharField(
                choices=[("VISA", "Visa"), ("MASTERCARD", "Mastercard")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="wallets",
            name="currency",
            field=models.CharField(
                choices=[("USD", "Usd"), ("EUR", "Eur"), ("RUB", "Rub")], max_length=3
            ),
        ),
    ]
