# Generated by Django 4.1.2 on 2022-11-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_alter_transaction_receiver_alter_transaction_sender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[("PAID", "Paid"), ("FAILED", "Failed")],
                default="FAILED",
                max_length=6,
            ),
        ),
    ]
